### ISSUE TITLE
typedoc : package.json - Request script to generate the pdf

### ISSUE THREAD

**Issue by yboujraf** [Agreon/typedoc-plugin-pdf-export#4]
Dear @Agreon ,

I followed your repo and how to install the plugin but when executing the script I have html files.

Would you like to share the command to generate the pdf file pls ?

Best Regards,
Youssef

**Comment by Agreon** [comment]
Dear Youssef,

In general these html files are generated by typedoc on default. There are several things to consider:

1. Check your main folder. The pdf is generated in the main folder named "export.pdf".
2. Check whether the plugin is used. On execution, the typedoc-script lists all active plugins. There should be a line like "Loaded plugin "<PROJECT_PATH>/node_modules/typedoc-plugin-pdf-export"
3. Check the typedoc-version. I'm currently using typedoc@0.15.6. Maybe that is causing problems


Otherwise this is my command: 
`typedoc --listInvalidSymbolLinks --name TestProject --mode \"module\" --exclude \"**/+(node_modules|test|loader|dist)/**\" --out ./doc/ .`

Best,
Daniel

**Comment by Agreon** [comment]
I would also recommend installing the plugin [typedoc-plugin-external-module-name](https://github.com/christopherthielen/typedoc-plugin-external-module-name)

**Comment by yboujraf** [comment]
Dear @Agreon 

I am using the latest version of typedoc : "typedoc": "^0.17.6",

Best Regards
Youssef

**Comment by yboujraf** [comment]
@Agreon 

plugin typedoc-plugin-external-module-name I have an error message

```
desk01@BY_DESKTOP_01 MINGW64 /c/Git/by-research/smh - connectors/smh-connector-lib/smh-template-connector-lib (feature/SMH-66-add-connector-client-server-socke)
$ npm install -D typedoc-plugin-external-module-name
npm WARN @typescript-eslint/eslint-plugin-tslint@2.23.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN typedoc-plantuml@1.4.1 requires a peer of typedoc@^0.4.1 but none is installed. You must install peer dependencies yourself.

+ typedoc-plugin-external-module-name@3.1.0
added 2 packages from 1 contributor, removed 82 packages and audited 1785437 packages in 10.3s

29 packages are looking for funding
  run `npm fund` for details

found 1234 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

desk01@BY_DESKTOP_01 MINGW64 /c/Git/by-research/smh - connectors/smh-connector-lib/smh-template-connector-lib (feature/SMH-66-add-connector-client-server-socke)
$ typedoc
Loaded plugin C:\Git\by-research\smh - connectors\smh-connector-lib\smh-template-connector-lib\node_modules\typedoc-neo-theme
Loaded plugin C:\Git\by-research\smh - connectors\smh-connector-lib\smh-template-connector-lib\node_modules\typedoc-plantuml
Loaded plugin C:\Git\by-research\smh - connectors\smh-connector-lib\smh-template-connector-lib\node_modules\typedoc-plugin-external-module-name
Loaded plugin C:\Git\by-research\smh - connectors\smh-connector-lib\smh-template-connector-lib\node_modules\typedoc-plugin-markdown
Loaded plugin C:\Git\by-research\smh - connectors\smh-connector-lib\smh-template-connector-lib\node_modules\typedoc-plugin-pages

Using TypeScript 3.7.2 from C:\Users\ybouj\AppData\Roaming\npm\node_modules\typescript\lib
C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:194
    return node['name'] && (ts.isIdentifierOrPrivateIdentifier(node['name']) ||
                               ^

TypeError: ts.isIdentifierOrPrivateIdentifier is not a function
    at isNamedNode (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:194:32)
    at Context.getSymbolAtLocation (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:47:24)
    at Object.createDeclaration (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\factories\declaration.js:61:32)
    at ClassConverter.convert (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\class.js:28:34)
    at Converter.convertNode (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\converter.js:116:53)
    at C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\block.js:58:32
    at Array.forEach (<anonymous>)
    at BlockConverter.convertStatements (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\block.js:56:29)
    at C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\block.js:43:26
    at Context.withScope (C:\Users\ybouj\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:108:9)```

**Comment by yboujraf** [comment]
@Agreon 

I I execute your script I have also this error 👍 

```
desk01@BY_DESKTOP_01 MINGW64 /c/Git/by-research/smh - connectors/smh-connector-lib/smh-template-connector-lib (feature/SMH-66-add-connector-client-server-socke)
$ typedoc --listInvalidSymbolLinks --name TestProject --mode \"module\" --exclude \"**/+(node_modules|test|loader|dist)/**\" --out ./doc/ .
bash: syntax error near unexpected token `('
````

from my side I am using .ts config file

````
module.exports = {
    inputFiles: ['./src/'],
    mode: 'file',
    includeDeclarations: true,
    tsconfig: 'tsconfig.json',
    out: './docs/dist/docs-pdf/',
    excludePrivate: false,
    excludeProtected: false,
    excludeExternals: true,
    readme: './README.md',
    name: myproject',
    ignoreCompilerErrors: true,
    plugin: 'none',
    listInvalidSymbolLinks: true,
    entryPoint: './README.md',
    categorizeByGroup: true,
    media: './medias',
    version: '',
    theme: 'default'
};
```

May be you could help me to update him. But I can't see the name of the plugin in your command line. Is it possible to combine more than one plugin at time ?

Best Regards,
Youssef
